---
- hosts: all

  vars:
    downloads: ~/.ansible-downloads/

    pre_tasks:
    - name: Include macOS defaults configuration
      include_vars: "{{ item }}"
      with_fileglob:
      - "{{ playbook_dir }}/macos_defaults.yml"
      tags: ["always"]

    homebrew_installed_packages:
    - argo
    - direnv
    - graphviz
    - jq
    - k9s
    - yq

    homebrew_cask_appdir: /Applications
    homebrew_cask_apps:
    - devtoys
    - rancher
    - firefox
    - miniforge
    - slack
    - rstudio
    - coolterm
    - db-browser-for-sqlite
    # - folding-at-home
    - github
    - grandperspective
    - iina
    # - microsoft-teams
    - raspberry-pi-imager
    - visual-studio-code

    mas_installed_apps:
    - { id: 1122008420, name: "Table Tool" }
    - { id: 1084713122, name: "Markoff" }
    - { id: 1282504627, name: "Mimeo Photos" }
    - { id: 1544743900, name: "Hush" }
    - { id: 407963104, name: "Pixelmator" }
    - { id: 1278508951, name: "Trello" }
    - { id: 497799835, name: "Xcode" }
    - { id: 937984704, name: "Amphetamine" }
    - { id: 882637653, name: "Debit & Credit" }

    dockitems_remove:
    - TV
    - Podcasts
    - News
    - "App Store"
    - Contacts
    - Maps
    - Calendar
    # dockitems_persist:
    # - name: "Visual Studio Code"
    #   path: "/Applications/Visual Studio Code.app/"
    #   pos: 6
    
    dotfiles_repo: https://github.com/goatsweater/dotfiles.git
    dotfiles_repo_accept_hostkey: true
    dotfiles_repo_version: main
    dotfiles_repo_local_destination: ~/Development/dotfiles
    dotfiles_files:
    - .gitignore

  roles:
  - role: elliotweiser.osx-command-line-tools
  - role: geerlingguy.mac.homebrew
    tags: ['homebrew']
  - role: geerlingguy.mac.mas
    tags: ['mas']
  - role: geerlingguy.mac.dock
    tags: ['dock']
  - role: geerlingguy.dotfiles
    tags: ['dotfiles']
  - role: lafarer.osx-defaults
    tags: ['defaults']
  - role: gantsign.visual-studio-code-extensions
    tags: ['vscode']
    users:
    - username: goatsweater
      visual_studio_code_extensions:
      - wholroyd.jinja
      - ms-python.python
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - redhat.vscode-yaml
      - lextudio.restructuredtext
      - ms-toolsai.jupyter

